name: Simple TS/Node/Fastify CICD
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: job name is hello world
        run: echo 'Salam world'
