name: fastify-test
on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  HELLO: salam
jobs:
  env:
    HELLO_TEST: ${{vars.NODE_ENV}}
  test:
    runs-on: ubuntu-latest
    environment: development

    steps:
      # - name: get codes
      #   uses: actions/checkout@v4
      # - name: install pnpm
      #   uses: pnpm/action-setup@v4
      #   with:
      #     run_install: |
      #       - recursive: false
      #         args: [--frozen-lockfile, --strict-peer-dependencies]
      # - name: Install Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      #     cache: 'pnpm'
      # - name: pnpm version and node version
      #   run: echo "node:$(node --version) - pnpm:$(pnpm --version)"

      # - name: run tests
      #   run: pnpm test
      - name: echo envs
        run: echo ${{env}}
      - name: echo vars
        run: echo ${{vars}}
